name: Compile and publish binaries whenever a new release is cut

permissions:
  contents: write

on:
  release:
    types: [published, released]

jobs:
  compile-and-publish:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-latest
          - target: aarch64-apple-darwin
            runner: macos-latest
          - target: aarch64-pc-windows-msvc
            runner: windows-latest
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
          - target: x86_64-apple-darwin
            runner: macos-latest
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/install-action@cross
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: babichjacob-experimenting-with-binstall
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
